Invoice/urls.py
from django.urls import path, register_converter
from .views import (
    download_invoice,
    delete_project,
    delete_fee,
    modify_invoice,
    modify_project,
    modify_fee,
    add_projectAndFeesToInvoice,
    add_feesToProject,
    create_creditNoteOfInvoice,
    add_invoice,
    add_invoice_for,
    validate_invoice,
    delete_invoice,
    add_estimate,
    add_estimate_for,
    invoice_estimate,
    delete_payment,
    download_receipt,
    InvoiceDetailView,
    InvoiceListView,
    EstimateListView,
    CreditNoteListView,
    PaymentCreateView,
    PaymentUpdateView,
    PaymentDetailView,
    PaymentListView,
)

from Core.views import DateConverter


register_converter(DateConverter, 'date')
app_name = 'Invoice'
urlpatterns = [
    path('', InvoiceListView.as_view(), name='index'),
    path('estimates', EstimateListView.as_view(), name='estimates'),
    path('creditNotes', CreditNoteListView.as_view(), name='creditNotes'),
    path(
        '<int:invoicer>/<int:invoicee>/<date:beginDate>/<date:endDate>',
        InvoiceListView.as_view(),
        name='index',
    ),
    path('addInvoice/', add_invoice, name='add-invoice'),
    path('addEstimate/', add_estimate, name='add-estimate'),
    path(
        'addInvoiceFor/<int:invoicee>',
        add_invoice_for,
        name='add-invoice-for',
    ),
    path(
        'addEstimateFor/<int:invoicee>',
        add_estimate_for,
        name='add-estimate-for',
    ),
    path('deleteInvoice/<int:invoice>', delete_invoice, name='delete-invoice'),
    path(
        'invoiceEstimate/<int:invoice>',
        invoice_estimate,
        name='invoice-estimate',
    ),
    path(
        'invoiceValidate/<int:invoice>',
        validate_invoice,
        name='validate-invoice',
    ),
    path(
        'createCreditNote/<int:invoice>',
        create_creditNoteOfInvoice,
        name='create-creditNote',
    ),
    path('preview/<slug:pk>', InvoiceDetailView.as_view(), name='preview'),
    path('download/<int:invoice>', download_invoice, name='download'),
    path('modify/<int:invoice>', modify_invoice, name='modify'),
    path('modifyProject/<int:project>', modify_project, name='modifyProject'),
    path('modifyFee/<int:fee>', modify_fee, name='modifyFee'),
    path(
        'addFeesToProject/<int:project>',
        add_feesToProject,
        name='addFeesToProject',
    ),
    path(
        'addProjectAndFees/<int:invoice>',
        add_projectAndFeesToInvoice,
        name="addProjectAndFeesToInvoice",
    ),
    path('deleteProject/<int:project>', delete_project, name='deleteProject'),
    path('deleteFee/<int:fee>', delete_fee, name='deleteFee'),
    path('updateFee/<int:fee>', modify_fee, name='updateFee'),
    path('payments', PaymentListView.as_view(), name='payments'),
    path('payment/<slug:pk>', PaymentDetailView.as_view(), name='payment'),
    path('addPayment', PaymentCreateView.as_view(), name='add-payment'),
    path(
        'updatePayment/<slug:pk>',
        PaymentUpdateView.as_view(),
        name='update-payment',
    ),
    path(
        'deletePayment/<int:payment>',
        delete_payment,
        name='delete-payment',
    ),
    path(
        'downloadReceipt/<int:payment>',
        download_receipt,
        name='download-receipt',
    ),
]

Invoicee/urls.py
from django.urls import path, register_converter
from .views import (
    InvoiceeListView,
    PrivateInvoiceeListView,
    InvoiceeDetailView,
    InvoiceeCreateView,
    InvoiceeUpdateView,
    PrivateInvoiceeCreateView,
)

from Core.views import DateConverter


register_converter(DateConverter, 'date')
app_name = 'Invoicee'
urlpatterns = [
    path('', InvoiceeListView.as_view(), name='invoicees'),
    path('private', PrivateInvoiceeListView.as_view(), name='pinvoicees'),
    path('detail/<slug:pk>', InvoiceeDetailView.as_view(), name='invoicee'),
    path('addInvoicee', InvoiceeCreateView.as_view(), name='add-invoicee'),
    path(
        'addPrivateInvoicee',
        PrivateInvoiceeCreateView.as_view(),
        name='add-private-invoicee',
    ),
    path(
        'modify/<slug:pk>',
        InvoiceeUpdateView.as_view(),
        name='modify-invoicee',
    ),
    path(
        'addInvoicee',
        InvoiceeCreateView.as_view(),
        name='add-invoicee',
    ),
]

home/urls.py
from django.urls import path, register_converter
from .views import (
    index,
    register_user,
    register_success,
)
from Core.views import DateConverter

register_converter(DateConverter, 'date')
app_name = 'home'
urlpatterns = [
    path('', index, name='index'),
    path(
        '<int:invoicer>/<date:beginDate>/<date:endDate>',
        index,
        name='index',
    ),
    path('register/', register_user, name='register'),
    path('registerSuccess/', register_success, name='registerSuccess')
]

Invoice/models.py
from datetime import date
from decimal import Decimal

from django.urls import reverse_lazy
from django.db.models import (
    Q, F, When, Case, Value, Avg, Sum,
    Model,
    ForeignKey,
    IntegerField,
    CharField,
    DateField,
    DecimalField,
    GeneratedField,
    ManyToManyField,
    CASCADE,
)
from django.db.models.lookups import LessThanOrEqual
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
)
from django.utils.translation import gettext_lazy as _
from django.db.models.expressions import DatabaseDefault
from django.core.exceptions import ValidationError
from simple_history.models import HistoricalRecords

from Core.models import (
    PaymentMethod,
    SystemCurrency,
    InvoiceStates,
)
from Core.utils import (
    get_currency_symbol,
)


class Invoice(Model):

    invoicer = ForeignKey(
        'Invoicer.Invoicer',
        on_delete=CASCADE,
        verbose_name=_('INVOICER'),
    )
    invoicee = ForeignKey(
        'Invoicee.Invoicee',
        on_delete=CASCADE,
        verbose_name=_('INVOICEE'),
    )
    bankAccount = ForeignKey(
        'Invoicer.BankAccount',
        on_delete=CASCADE,
        verbose_name=_('BankAccount'),
        null=True,
        blank=True,
    )
    count = IntegerField(
        db_default=0,
        blank=True,
        null=True,
        verbose_name=_('NUMBRE'),
    )
    baseCurrency = CharField(
        max_length=4,
        db_default='',
        choices=SystemCurrency,
        default=SystemCurrency.MAD,
        verbose_name=_('BaseCurrency'),
    )
    dueDate = DateField(
        db_default=date.today(),
        verbose_name=_('DueDate'),
        blank=True,
        null=True,
    )
    facturationDate = DateField(
        db_default=date.today(),
        verbose_name=_('FacturationDate'),
        blank=True,
        null=True,
    )
    paymentMethod = CharField(
        max_length=2,
        choices=PaymentMethod,
        default=PaymentMethod.CASH,
        verbose_name=_('PaymentMethod'),
    )
    salesAccount = IntegerField(
        db_default=0,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(99999999),
        ],
        verbose_name=_('SalesAccount'),
    )
    vatAccount = IntegerField(
        db_default=0,
        verbose_name=_('VATAccount'),
        validators=[
            MinValueValidator(0),
            MaxValueValidator(99999999),
        ],
    )
    state = IntegerField(
        db_default=0,
        choices=InvoiceStates,
        default=InvoiceStates.DRAFT,
        verbose_name=_('State'),
    )
    # 0: Draft or Estimate
    # 1: Validated, not paid and not overdue
    # 2: Validated and fully Paid
    # 3: Validated, not paid and overdue
    status = GeneratedField(
        expression=Case(
            When(Q(state__in=[0, 1]), then=Value(0)),
            When(
                Q(LessThanOrEqual(F('owedAmount'), F('paidAmount'))),
                then=Value(2),
            ),
            When(dueDate__lte=date.today(), then=Value(3)),
            default=1,
        ),
        output_field=IntegerField(),
        db_persist=True,
        verbose_name=_('Status'),
    )
    paidAmount = DecimalField(
        decimal_places=2,
        max_digits=8,
        db_default=0,
        verbose_name=_('PaidAmount'),
        null=True,
        blank=True,
    )
    owedAmount = DecimalField(
        decimal_places=2,
        max_digits=8,
        db_default=0,
        verbose_name=_('OwedAmount'),
        null=True,
        blank=True,
    )

    def __str__(self):
        if self.state == 0:
            return f'{self.invoicer}|{self.invoicee}:{_('BState')}{self.id}'
        elif self.state == 1:
            return f'{self.invoicer}|{self.invoicee}:{_('DState')}{self.id}'
        elif self.state == 4:
            return f'{self.invoicer}|{self.invoicee}:{_('CNState')}{self.count}'
        else:
            repr = f'{self.invoicer}|{self.invoicee}:{_('FState')}{self.count}'
            if self.owedAmount > 0:
                if self.owedAmount <= self.paidAmount:
                    return repr + '-'
                currencySymbol = get_currency_symbol(self.baseCurrency)
                repr += f':{self.owedAmount - self.paidAmount}{currencySymbol}'
            return repr.replace('\n', ' ')

    @property
    def number(self):
        if self.state == 0:
            return f'{date.today().year}-{_('BState')}-{self.id}'
        elif self.state == 1:
            return f'{date.today().year}-{_('DState')}-{self.id}'
        elif self.state == 4:
            return f'{self.facturationDate.year}-{_('CNSTATE')}-{self.count}'
        else:
            return f'{self.facturationDate.year}-{_('FState')}-{self.count}'

    def clean(self):
        if (
            self.dueDate is None
            or self.facturationDate is None
            or isinstance(self.dueDate, DatabaseDefault)
            or isinstance(self.facturationDate, DatabaseDefault)
        ) and self.state != 1:
            raise ValidationError(
                _('DueANDFacturationDATESareMANDATORYForINVOICES')
            )
        if self.dueDate is not None and self.facturationDate is not None:
            if self.dueDate < self.facturationDate:
                raise ValidationError(_('DueDateIsLessThanFacturationDate'))

    def save(self, *args, **kwargs):
        invoices = Invoice.objects
        self.description = f'{self.invoicer}|{self.invoicee}'
        if self.state == 0 or self.state == 1:
            self.count = None
        elif self.state == 4 and (
            self.count is None
            or isinstance(self.count, DatabaseDefault)
            or self.count == 0
        ):
            invoices = invoices.filter(
                state=4,
            ).filter(
                invoicer=self.invoicer,
            ).filter(
                facturationDate__gte=f'{self.facturationDate.year}-01-01',
            ).filter(
                facturationDate__lte=f'{self.facturationDate.year}-12-31',
            )
            self.count = 1 if invoices.count() == 0 else max(
                invoice.count for invoice in invoices
            ) + 1
        elif self.state == 2 and (
            self.count is None
            or isinstance(self.count, DatabaseDefault)
            or self.count == 0
        ):
            invoices = invoices.filter(
                state__in=[2, 3],
            ).filter(
                invoicer=self.invoicer,
            ).filter(
                facturationDate__gte=f'{self.facturationDate.year}-01-01',
            ).filter(
                facturationDate__lte=f'{self.facturationDate.year}-12-31',
            )
            self.count = 1 if invoices.count() == 0 else max(
                invoice.count for invoice in invoices
            ) + 1
        super(Invoice, self).save()

    @property
    def outstandingAmount(self):
        if self.owedAmount > 0:
            return self.owedAmount - self.paidAmount
        else:
            return 0

    @property
    def wellFormed(self):
        wellFormed = self.project_set.count() > 0
        return wellFormed and all(
            project.fee_set.count() > 0 for project in self.project_set.all()
        )

    @property
    def downloadable(self):
        return self.wellFormed

    @property
    def totalBeforeVAT(self):
        return sum(
            project.totalBeforeVAT for project in self.project_set.all()
        )

    @property
    def totalVAT(self):
        return sum(project.totalVAT for project in self.project_set.all())

    @property
    def totalAfterVAT(self):
        return sum(project.totalAfterVAT for project in self.project_set.all())

    @property
    def avgVAT(self):
        if self.project_set.all().count() > 0:
            return (
                sum(project.avgVAT for project in self.project_set.all())
                / self.project_set.count()
            )
        else:
            return 0

    class Meta:
        verbose_name = _('INVOICE')
        verbose_name_plural = _('INVOICES')


class Project(Model):

    invoice = ForeignKey(
        'Invoice.Invoice',
        on_delete=CASCADE,
        verbose_name=_('INVOICE'),
    )
    title = CharField(
        max_length=100,
        db_default='',
        verbose_name=_('Title'),
    )

    def delete(self, *args, **kwargs):
        invoice = self.invoice
        invoice.owedAmount -= self.totalAfterVAT
        invoice.save()
        super().delete(*args, **kwargs)

    @property
    def totalBeforeVAT(self):
        return self.fee_set.aggregate(totalBeforeVAT=Sum('rateUnit'))[
            'totalBeforeVAT'
        ]

    @property
    def totalVAT(self):
        return round(
            self.fee_set.annotate(
                VAT=F('rateUnit')*F('vat')/100
            ).aggregate(
                total=Sum('VAT')
            )['total'],
            2,
        )

    @property
    def totalAfterVAT(self):
        return self.totalBeforeVAT + self.totalVAT

    @property
    def avgVAT(self):
        return self.fee_set.aggregate(averageVAT=Avg('vat'))['averageVAT']

    @property
    def numFees(self):
        return self.fee_set.count()

    def __str__(self):
        return f'{self.invoice}|{self.title}'

    class Meta:
        verbose_name = _('PROJECT')
        verbose_name_plural = _('PROJECTS')


class Fee(Model):

    project = ForeignKey(
        'Invoice.Project',
        on_delete=CASCADE,
        verbose_name=_('PROJECT'),
    )
    rateUnit = DecimalField(
        db_default=0,
        decimal_places=2,
        max_digits=8,
        verbose_name=_('RateUnit')
    )
    count = IntegerField(db_default=0, verbose_name=_('COUNT'))
    vat = IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        db_default=0,
        verbose_name=_('VAT'),
    )
    description = CharField(
        max_length=100,
        db_default='',
        verbose_name=_('Description'),
    )
    bookKeepingAmount = DecimalField(

Invoice/templates/Invoice-index-partial.html
{% load i18n %}
<h1>
    {% translate 'InvoiceListView' %}
    {% if payment %}
    {% blocktranslate with payment=payment %}
    of the Payment {{ payment }}  
    {% endblocktranslate %}
    {% elif invoicee %}
    {% blocktranslate with name=invoicee.name %}
    of the INVOICEE {{ name }}  
    {% endblocktranslate %}
    {% endif %}
</h1>
{% if messages %}
<div class="messages-content">
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}{% translate 'Error' %}: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}
<div class="filter-form-wrapper">
    <form 
        hx-push-url="true" 
        hx-indicator="#indicator"
        hx-get=
        {% if invoicee %}
        "{% url 'Invoicee:invoicee' invoicee.id %}"
        {% elif payment %}
        "{% url 'Invoice:payment' payment.id %}"
        {% else %}
        "{% url 'Invoice:index' %}"
        {% endif %}
        hx-swap="innerHTML" 
        hx-target="main" 
        class="filter-form">
        <div class="form-main">
            <h2>{% translate "HomeCONTROLSText" %}</h2>
            {% csrf_token %}
            {{ form }}
        </div>
        <div class="form-footer">
            <button class="submit-button" type="submit">{% translate "ApplyFilter" %}</button>
        </div>
    </form>
</div>
{% if payment %}
<div class="item-list">
    <div class="item-list-header">{% translate 'PaymentDetail' %}</div>
    <table>
        <thead>
            <tr>
                <th style="width: 300px" nonce={{ request.csp_nonce }}>{% translate 'INVOICEE' %}</th>
                <th>{% translate 'PaymentDay' %}</th>
                <th>{% translate 'PaidAmount' %}</th>
                <th>{% translate 'PaidInvoices' %}</th>
                <th>{% translate 'BankAccount' %}</th>
            </tr>
        </thead>
        <tbody>
            {% include './payment-list-item.html' with payment=payment %}
        </tbody>
    </table>
</div>
{% elif invoicee %}
<div class="item-list">
    <div class="item-list-header">{% translate 'INVOICEEDetail' %}</div>
    <table>
        <thead>
            <tr>
                <th>{% translate 'Name' %}</th>
                <th>{% translate 'Address' %}</th>
                {% if private %}
                <th>{% translate 'CIN' %}</th>
                {% else %}
                <th>{% translate 'ICE' %}</th>
                {% endif %}
                <th>{% translate 'OutStandingAmount' %}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                {% include './Invoicee-list-item.html' with invoicee=invoicee %}
            </tr>
        </tbody>
    </table>
</div>
{% endif %}
<div class="item-list">
    {% if payment %}
    <div class="item-list-header">{% translate 'INVOICESOfPayment' %}</div>
    {% elif invoicee %}
    <div class="item-list-header">{% translate 'INVOICESOfInvoicee' %}</div>
    {% endif %}
        {% if invoice_list %}
        <table>
            <thead>
                <tr>
                    {% if not invoicee %}
                    <th style="width: 300px" nonce={{ request.csp_nonce }}>{% translate 'INVOICEE' %}</th>
                    {% endif %}
                    <th>{% translate 'InvoiceNumber' %}</th>
                    <th>{% translate 'TotalAfterVAT' %}</th>
                    <th>{% translate 'TBPaid' %}</th>
                    <th>{% translate 'Currency' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for invoice in invoice_list %}
                {% include './Invoice-list-item.html' with invoicee=invoicee payment=payment invoice=invoice %}
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
        <div class="item-list-footer">
            {% if not payment %}
            <button 
                class="extensive-button"
                type="button"
                {% if invoicee %}
                hx-get="{% url 'Invoice:add-invoice-for' invoicee.id %}"
                {% else %}
                hx-get="{% url 'Invoice:add-invoice' %}"
                {% endif %}
                hx-target="#invoice-form-dialog"
                hx-on:click="document.getElementById('invoice-form-dialog').showModal();"
                hx-swap="innerHTML">
                {% include './symbols/file-plus.svg' %}
                {% if invoicee %}
                <span class="text">{% translate 'AddNewInoivceToINVOICEE' %}</span>
                {% else %}
                <span class="text">{% translate 'AddNewInvoice' %}</span>
                {% endif %}
            </button>
            <button 
                class="extensive-button"
                type="button"
                {% if invoicee %}
                hx-get="{% url 'Invoice:add-estimate-for' invoicee.id %}"
                {% else %}
                hx-get="{% url 'Invoice:add-estimate' %}"
                {% endif %}
                hx-target="#invoice-form-dialog"
                hx-on:click="document.getElementById('invoice-form-dialog').showModal();"
                hx-swap="innerHTML">
                {% include './symbols/shopping-bag.svg' %}
                {% if invoicee %}
                <span class="text">{% translate 'AddNewEstimateToINVOICEE' %}</span>
                {% else %}
                <span class="text">{% translate 'AddNewEstimate' %}</span>
                {% endif %}
            </button>
        </div>
    </div>
{% endif %}

Invoice/templates/Invoice-list-item.html
{% load i18n %}
<tr id="table-row-{{ invoice.id }}">
    {% if managerHasMultipleInvoicers %}
    <td 
        nonce="{{ request.nonce_csp_nonce }}"
        style="padding-left: 5px"
        {% if invoice.state == 3 %}
        class="cleared"
        {% elif invoice.status == 3 %}
        class="overdue"
        {% endif %}
    >{{ invoice.invoicer }}</td>
    {% endif %}
    {% if not invoicee %}
    <td 
        nonce="{{ request.nonce_csp_nonce }}"
        style="padding-left: 5px"
        {% if invoice.state == 3 %}
        class="cleared"
        {% elif invoice.status == 3 %}
        class="overdue"
        {% endif %}
    >{{ invoice.invoicee }}</td>
    {% endif %}
    <td 
        helptext="{% translate 'InvoiceNumber' %}"
        {% if invoice.state == 3 %}
        class="cleared"
        {% elif invoice.status == 3 %}
        class="overdue"
        {% endif %}
    >{{ invoice.number }}</td>
    <td 
        helptext="{% translate 'TotalAfterVAT' %}"
        {% if invoice.state == 3 %}
        class="cleared"
        {% elif invoice.status == 3 %}
        class="overdue"
        {% endif %}
    >{{ invoice.totalAfterVAT }}</td>
    <td 
        helptext="{% translate 'TotalAfterVAT' %}"
        {% if invoice.state == 3 %}
        class="cleared"
        {% elif invoice.status == 3 %}
        class="overdue"
        {% endif %}
    >{{ invoice.outstandingAmount }}</td>
    <td 
        {% if invoice.state == 3 %}
        class="cleared"
        {% elif invoice.status == 3 %}
        class="overdue"
        {% endif %}
    >{{ invoice.baseCurrency }}</td>
    {% if invoice.wellFormed %}
    <td class="borderless">
        <button 
            helptext="{% translate 'InvoicePreviewExplanation' %}"
            type="button"
            hx-get="{% url 'Invoice:preview' invoice.id %}"
            hx-indicator="#indicator"
            hx-push-url="true"
            hx-indicator="#indicator"
            hx-swap="innerHTML"
            hx-target="main">
            {% include './symbols/eye.svg' %}
        </button>
    </td>
    {% endif %}
    {% if invoice.state == 0 or invoice.state == 1 %}
    <td class="borderless">
        <a href="{% url 'Invoice:modify' invoice.id %}" helptext="{% translate 'InvoiceModifyExplanation' %}">
            {% include './symbols/edit.svg' %}
        </a>
    </td>
    {% endif %}
    {% if invoice.wellFormed and invoice.state == 0 %}
    <td class="borderless">
        <button
            hx-get="{% url 'Invoice:validate-invoice' invoice.id %}"
            hx-indicator="#indicator"
            hx-swap="outerHTML"
            helptext="{% translate 'ValidateInvoiceExplantion' %}"
            hx-target="#table-row-{{ invoice.id }}">
            {% include './symbols/check-square.svg' %}
        </button>
    </td>
    {% endif %}
    {% if invoice.wellFormed and invoice.state == 1 %}
    <td class="borderless">
        <button 
            hx-get="{% url 'Invoice:invoice-estimate' invoice.id %}"
            hx-indicator="#indicator"
            hx-swap="outerHTML"
            hx-target="#table-row-{{ invoice.id }}"
            helptext="{% translate 'InvoiceEstimateExplanation' %}">
            {% include './symbols/check-circle.svg' %}
        </button>
    </td>
    {% endif %}
    {% if invoice.state == 2 and invoice.paymentMethod != 'CN' %}
    <td class="borderless">
        <button
            hx-get="{% url 'Invoice:create-creditNote' invoice.id %}"
            hx-swap="innerHTML"
            hx-indicator="#indicator"
            helptext="{% translate 'CreateCreditNoteExplanation' %}"
            hx-target="main">
            {% include './symbols/corner-down-left.svg' %}
        </button>
    </td>
    {% endif %}
    {% if invoice.state == 0 or invoice.state == 1 %}
    <td class="borderless">
        <button 
            hx-get="{% url 'Invoice:delete-invoice' invoice.id %}"
            hx-swap="innerHTML"
            hx-indicator="#indicator"
            hx-target="main"
            helptext="{% translate 'DeleteInvoiceButtonExplanation' %}">
            {% include './symbols/trash.svg' %}
        </button>
    </td>
    {% endif %}
    {% if invoice.downloadable %}
    <td class="borderless">
        <a href="{% url 'Invoice:download' invoice.id %}" helptext="{% translate 'DownloadInvoiceButtonExplanation' %}">
            {% include './symbols/download.svg' %}
        </a>
    </td>
    {% endif %}
</tr>

Invoice/templates/Payment-list-item.html
{% load i18n %}
<tr>
    <td>{{ payment.payor }}</td>
    <td>{{ payment.paymentDay }}</td>
    <td>{{ payment.paidAmount }}</td>
    <td>
        <ul>
        {% for invoice in payment.invoice.all %}
            <li><button 
                hx-get="{% url 'Invoice:preview' invoice.id %}"
                hx-swap="innerHTML"
                hx-target="main"
                helptext="{% translate 'PreviewInvoice' %}"
                class="invoice-button"
            >{{ invoice.number }}</button></li>
        {% endfor %}
        </ul>
    </td>
    <td>{% if payment.bankAccount %}{{ payment.bankAccount }}{% else %}{% translate 'NoBankAccount' %}{% endif %}</td>
    <td class="borderless">
        <button 
            hx-get="{% url 'Invoice:payment' payment.id %}"
            hx-swap="innerHTML"
            hx-target="main"
            hx-push-url="true"
            helptext="{% translate 'ViewPaymentDetailButtonExplanation' %}">
            {% include './symbols/eye.svg' %}
        </button>
    </td>
    <td class="borderless">
        <button 
            hx-get="{% url 'Invoice:update-payment' payment.id %}" 
            hx-swap="innerHTML" 
            hx-target="#payment-form-dialog"
            hx-on:click="document.getElementById('payment-form-dialog').showModal();"
            helptext="{% translate 'PaymentModifyExplanation' %}">{% include './symbols/edit.svg' %}</button>
    </td>
    <td class="borderless">
        <a href="{% url 'Invoice:download-receipt' payment.id %}" helptext="{% translate 'DownloadReceiptButtonExplanation' %}">
            {% include './symbols/download.svg' %}
        </a>
    </td>
    <td class="borderless">
        <button 
            hx-delete="{% url 'Invoice:delete-payment' payment.id %}"
            hx-confirm="{% translate 'PaymentDeleteConfimMessage' %}"
            hx-swap="innerHTML"
            hx-target="main"
            helptext="{% translate 'DeletePaymentButtonExplanation' %}">
            {% include './symbols/trash.svg' %}
        </button>
        <script nonce="{{ request.csp_nonce }}">
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
        </script>
    </td>
</tr>

Invoice/templates/Project-list-item.html
{% load i18n %}
<tr>
    <td>{{ fee.description }}</td>
    <td>{{ fee.vat }}%</td>
    <td>{{ fee.count }}</td>
    <td>{{ fee.rateUnit }}</td>
    <td>{{ fee.totalAfterVAT }}</td>
    <td class="borderless">
        {% if invoice.status == 0 or invoice.status == 1 %}
        <a href="{% url 'Invoice:modify' invoice.id %}" helptext="{% translate 'FeeModifyExplanation' %}"> {% include './symbols/edit.svg' %} </a>
        {% endif %}
    </td>
    {% if numFees > 1 %}
    <td class="borderless">
        {% if invoice.state == 0 or invoice.state == 1 %}
        <button 
            hx-indicator="#indicator"
            hx-get="{% url 'Invoice:delete-invoice' invoice.id %}"
            hx-swap="innerHTML"
            hx-target="main"
            helptext="{% translate 'DeleteFeeButtonExplanation' %}">
            {% include './symbols/trash.svg' %}
        </button>
        {% endif %}
    </td>
    {% endif %}
    <td class="borderless">
        {% if invoice.downloadable %}
        <a href="{% url 'Invoice:download' invoice.id %}" helptext="{% translate 'DownloadInvoiceButtonExplanation' %}">
            {% include './symbols/download.svg' %}
        </a>
        {% endif %}
    </td>
</tr>