Invoice/urls.py
from django.urls import path, register_converter
from .views import (
    download_invoice,
    delete_project,
    delete_fee,
    modify_invoice,
    modify_project,
    modify_fee,
    add_projectAndFeesToInvoice,
    add_feesToProject,
    create_creditNoteOfInvoice,
    add_invoice,
    add_invoice_for,
    validate_invoice,
    delete_invoice,
    add_estimate,
    add_estimate_for,
    invoice_estimate,
    delete_payment,
    download_receipt,
    InvoiceDetailView,
    InvoiceListView,
    EstimateListView,
    CreditNoteListView,
    PaymentCreateView,
    PaymentUpdateView,
    PaymentDetailView,
    PaymentListView,
)

from Core.views import DateConverter


register_converter(DateConverter, 'date')
app_name = 'Invoice'
urlpatterns = [
    path('', InvoiceListView.as_view(), name='index'),
    path('estimates', EstimateListView.as_view(), name='estimates'),
    path('creditNotes', CreditNoteListView.as_view(), name='creditNotes'),
    path(
        '<int:invoicer>/<int:invoicee>/<date:beginDate>/<date:endDate>',
        InvoiceListView.as_view(),
        name='index',
    ),
    path('addInvoice/', add_invoice, name='add-invoice'),
    path('addEstimate/', add_estimate, name='add-estimate'),
    path(
        'addInvoiceFor/<int:invoicee>',
        add_invoice_for,
        name='add-invoice-for',
    ),
    path(
        'addEstimateFor/<int:invoicee>',
        add_estimate_for,
        name='add-estimate-for',
    ),
    path('deleteInvoice/<int:invoice>', delete_invoice, name='delete-invoice'),
    path(
        'invoiceEstimate/<int:invoice>',
        invoice_estimate,
        name='invoice-estimate',
    ),
    path(
        'invoiceValidate/<int:invoice>',
        validate_invoice,
        name='validate-invoice',
    ),
    path(
        'createCreditNote/<int:invoice>',
        create_creditNoteOfInvoice,
        name='create-creditNote',
    ),
    path('preview/<slug:pk>', InvoiceDetailView.as_view(), name='preview'),
    path('download/<int:invoice>', download_invoice, name='download'),
    path('modify/<int:invoice>', modify_invoice, name='modify'),
    path('modifyProject/<int:project>', modify_project, name='modifyProject'),
    path('modifyFee/<int:fee>', modify_fee, name='modifyFee'),
    path(
        'addFeesToProject/<int:project>',
        add_feesToProject,
        name='addFeesToProject',
    ),
    path(
        'addProjectAndFees/<int:invoice>',
        add_projectAndFeesToInvoice,
        name="addProjectAndFeesToInvoice",
    ),
    path('deleteProject/<int:project>', delete_project, name='deleteProject'),
    path('deleteFee/<int:fee>', delete_fee, name='deleteFee'),
    path('updateFee/<int:fee>', modify_fee, name='updateFee'),
    path('payments', PaymentListView.as_view(), name='payments'),
    path('payment/<slug:pk>', PaymentDetailView.as_view(), name='payment'),
    path('addPayment', PaymentCreateView.as_view(), name='add-payment'),
    path(
        'updatePayment/<slug:pk>',
        PaymentUpdateView.as_view(),
        name='update-payment',
    ),
    path(
        'deletePayment/<int:payment>',
        delete_payment,
        name='delete-payment',
    ),
    path(
        'downloadReceipt/<int:payment>',
        download_receipt,
        name='download-receipt',
    ),
]

Invoicee/urls.py
from django.urls import path, register_converter
from .views import (
    InvoiceeListView,
    PrivateInvoiceeListView,
    InvoiceeDetailView,
    InvoiceeCreateView,
    InvoiceeUpdateView,
    PrivateInvoiceeCreateView,
)

from Core.views import DateConverter


register_converter(DateConverter, 'date')
app_name = 'Invoicee'
urlpatterns = [
    path('', InvoiceeListView.as_view(), name='invoicees'),
    path('private', PrivateInvoiceeListView.as_view(), name='pinvoicees'),
    path('detail/<slug:pk>', InvoiceeDetailView.as_view(), name='invoicee'),
    path('addInvoicee', InvoiceeCreateView.as_view(), name='add-invoicee'),
    path(
        'addPrivateInvoicee',
        PrivateInvoiceeCreateView.as_view(),
        name='add-private-invoicee',
    ),
    path(
        'modify/<slug:pk>',
        InvoiceeUpdateView.as_view(),
        name='modify-invoicee',
    ),
    path(
        'addInvoicee',
        InvoiceeCreateView.as_view(),
        name='add-invoicee',
    ),
]

home/urls.py
from django.urls import path, register_converter
from .views import (
    index,
    register_user,
    register_success,
)
from Core.views import DateConverter

register_converter(DateConverter, 'date')
app_name = 'home'
urlpatterns = [
    path('', index, name='index'),
    path(
        '<int:invoicer>/<date:beginDate>/<date:endDate>',
        index,
        name='index',
    ),
    path('register/', register_user, name='register'),
    path('registerSuccess/', register_success, name='registerSuccess')
]

Invoicee/models.py
from django.urls import reverse_lazy
from django.db.models import (
    Model,
    CharField,
    ForeignKey,
    IntegerField,
    TextChoices,
    BooleanField,
    Sum,
    CASCADE,
)
from django.db.models.expressions import F
from django.core.validators import (
    MaxValueValidator,
    MinValueValidator,
    RegexValidator,
)
from django.utils.translation import gettext_lazy as _

from Invoice.models import Invoice
from Core.utils import get_currency_symbol


class Invoicee(Model):

    class OperatingCountries(TextChoices):
        MOROCCO = 'MAR', _('MOROCCO')
        FRANCE = 'FR', _('FRANCE')

    is_person = BooleanField(default=False, verbose_name=_('IsPerson'))
    cin = CharField(
        max_length=15,
        verbose_name=_('CIN'),
        null=True,
        blank=True,
        help_text=_('CINHelpText'),
    )
    country = CharField(
        max_length=20,
        default=OperatingCountries.MOROCCO,
        choices=OperatingCountries,
        verbose_name=_('COUNTRY'),
    )
    invoicer = ForeignKey(
        'Invoicer.Invoicer',
        on_delete=CASCADE,
        blank=False,
        verbose_name=_('INVOICER'),
    )
    ice = CharField(
        max_length=16,
        validators=[
            RegexValidator(
                regex=r'\d{14,16}',
                message=_('ICEInvalid'),
            ),
        ],
        db_default='0'*15,
        unique=True,
        null=True,
        blank=True,
        verbose_name=_('SIRET/ICE'),
        help_text=_('ICEHelpText'),
    )
    name = CharField(
        max_length=30,
        db_default='',
        verbose_name=_('NAME'),
    )
    address = CharField(
        max_length=100,
        db_default='',
        validators=[
            RegexValidator(
                regex=r'.*,.*',
                message=_('ADDRESSInvalid'),
            ),
        ],
        verbose_name=_('ADDRESS'),
        help_text=_('AddressHelpText'),
    )
    bookKeepingNumber = IntegerField(
        db_default=0,
        validators=[
            MaxValueValidator(99999),
            MinValueValidator(0),
        ],
        verbose_name=_('BookKeepingAccount'),
    )

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse_lazy('Invoicee:invoicee', args=[self.id])

    @property
    def outStandingAmounts(self):
        invoices = self.invoice_set.filter(state=2).filter(owedAmount__gte=0)
        currencies = invoices.values('baseCurrency').distinct().values_list(
            'baseCurrency', flat=True
        )
        return [
            {
                'currency': get_currency_symbol(currency),
                'amount': invoices.filter(
                    baseCurrency=currency
                ).annotate(
                    tbpaid=F('owedAmount')-F('paidAmount')
                ).aggregate(
                    outstanding=Sum('tbpaid')
                )['outstanding']
            }
            for currency in currencies
        ]

    @property
    def paidAmounts(self):
        invoices = self.invoice_set.filter(state=2).filter(owedAmount__gte=0)
        currencies = invoices.values('baseCurrency').distinct()
        return [
            {
                'currency': get_currency_symbol(currency['baseCurrency']),
                'amount': invoices.filter(
                    baseCurrency=currency
                ).aggregate(
                    paid=Sum('paidAmount')
                )['paid']
            }
            for currency in currencies
        ]

    @property
    def owedAmounts(self):
        invoices = self.invoice_set.filter(state=2).filter(owedAmount__gte=0)
        currencies = invoices.values('baseCurrency').distinct()
        return [
            {
                'currency': get_currency_symbol(currency['baseCurrency']),
                'amount': invoices.filter(
                    baseCurrency=currency
                ).aggregate(
                    owed=Sum('owedAmount')
                )['owed']
            }
            for currency in currencies
        ]

    class Meta:
        verbose_name = _('INVOICEE')
        verbose_name_plural = _('INVOICEES')

Invoicee/templates/Invoicee-detail-partial.html
{% load i18n %}
{% include 'Invoice-index-partial.html' with invoicee=invoicee invoice_list=invoices form=form managerHasManyInvoicers=managerHasManyInvoicers %}

Invoicee/templates/Invoicee-detail.html
{% extends 'base.html' %}
{% block content %}
{% include 'Invoicee-detail-partial.html' %}
{% endblock %}

Invoicee/templates/Invoicee-form-partial.html
{% load i18n %}
    {% if not dialogForm %}
<div class="form-wrapper">
{% endif %}
<form 
    class="invoicee-form form"
    hx-post="
    {% if update %}
    {% url 'Invoicee:modify-invoicee' invoicee.id %}
    {% elif private %}
    {% url 'Invoicee:add-private-invoicee' %}
    {% else %}
    {% url 'Invoicee:add-invoicee' %}
    {% endif %}
    " 
    hx-trigger="submit"
    hx-indicator="#indicator"
    hx-swap="innerHTML"
    hx-target="main">
    <div class="form-header">
        {% if dialogForm %}
        <botton type="button" hx-on:click="document.getElementById('invoicee-form-dialog').close()" class="dialog-close-button" tabindex="0">
            {% include './symbols/x-square.svg' %}
        </botton>
        {% endif %}
    </div>
    <div class="form-main">
        {% csrf_token %}
        {{ form }}
    </div>
    <div class="form-footer">
        <button type="submit" class="dialog-submit-button">
            {% if update %}
            {% translate 'Save' %}
            {% else %}
            {% translate 'AddInvoicee' %}
            {% endif %}
        </button>
    </div>
</form>
{% if not dialogForm %}
<div class="form-wrapper">
{% endif %}

Invoicee/templates/Invoicee-form.html
{% extends 'base.html' %}
{% block content %}
{% include 'Invoicee-form-partial.html' %}
{% endblock %}

Invoicee/templates/Invoicee-index-partial.html
{% load i18n %}
<h1>{% translate 'INVOICEE' %}</h1>
{% if messages %}
<div class="messages-content">
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}{% translate 'Error' %}: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}
<div class="filter-form-wrapper">
    <form 
        hx-push-url="true" 
        hx-get=
        {% if private %}
        "{% url 'Invoicee:pinvoicees' %}" 
        {% else %}
        "{% url 'Invoicee:invoicees' %}" 
        {% endif %}
        hx-swap="innerHTML" 
        hx-target="main" 
        class="filter-form">
        <div class="form-main">
            <h2>{% translate "EnterNameToSearchForInvoicee" %}</h2>
            {% csrf_token %}
            {{ searchForm }}
        </div>
        <div class="form-footer">
            <button class="submit-button" type="submit">{% translate "ApplyFilter" %}</button>
        </div>
    </form>
</div>
<div class="item-list">
    {% if invoicee_list %}
    <table>
        <thead>
            <tr>
                {% if hasMultipleInvoicers %}
                <th>{% translate 'INVOICER' %}</th>
                {% endif %}
                <th>{% translate 'Name' %}</th>
                <th>{% translate 'Address' %}</th>
                {% if private %}
                <th>{% translate 'CIN' %}</th>
                {% else %}
                <th>{% translate 'ICE' %}</th>
                {% endif %}
                <th>{% translate 'OutStandingAmount' %}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for invoicee in invoicee_list %}
                {% include './Invoicee-list-item.html' with invoicee=invoicee %}
                {% endfor %}
            </tr>
        </tbody>
    </table>
    {% endif %}
    <div class="item-list-footer">
        {% if private %}
        <button 
            hx-indicator="#indicator"
            hx-get="{% url 'Invoicee:add-private-invoicee' %}" class="MainItem"
            hx-target="#invoicee-form-dialog"
            hx-on:click="document.getElementById('invoicee-form-dialog').showModal();"
            hx-swap="innerHTML"
        >{% translate 'AddPrivateInvoicee' %}</button>
        {% else %}
        <button 
            hx-indicator="#indicator"
            hx-get="{% url 'Invoicee:add-invoicee' %}" class="MainItem"
            hx-target="#invoicee-form-dialog"
            hx-on:click="document.getElementById('invoicee-form-dialog').showModal();"
            hx-swap="innerHTML"
        >{% translate 'AddInvoicee' %}</button>
        {% endif %}
    </div>
</div>

Invoicee/templates/Invoicee-index.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    {% translate 'INVOICEE' %}

{% endblock %}

Invoicee/templates/Invoicee-list-item.html
{% load i18n %}
<tr>
    {% if hasMultipleInvoicers %}
    <td>{{ invoicee.invoicer.name }}</td>
    {% endif %}
    <td>{{ invoicee.name }}</td>
    {% if invoicee.address|length > 15 %}
    <td><button
    helptext="{{ invoicee.address }}">{{ invoicee.address|slice:15 }}...
    </button></td>
    {% else %}
    <td>{{ invoicee.address }}</td>
    {% endif %}
    {% if private %}
    <td>{% if invoicee.cin %}{{ invoicee.cin }}{% else %}-{% endif %}</td>
    {% else %}
    <td>{% if invoicee.ice %}{{ invoicee.ice }}{% else %}-{% endif %}</td>
    {% endif %}
    <td>
        {% if invoicee.outStandingAmounts %}
        <ul>
        {% for outStandingAmount in invoicee.outStandingAmounts %}
        <li>{{ outStandingAmount.amount }}{{ outStandingAmount.currency }}</li>
        {% endfor %}
        </ul>
        {{ invoicee.outStandingAmount }}
        {% else %}-{% endif %}
    </td>
    <td class="borderless">
        <button 
            helptext="{% translate 'InvoiceePreviewExplanation' %}"
            type="button"
            hx-get="{% url 'Invoicee:invoicee' invoicee.id %}"
            hx-push-url="true"
            hx-swap="innerHTML"
            hx-target="main">
            {% include './symbols/eye.svg' %}
        </button>
    </td>
    <td class="borderless">
        <button 
            hx-get="{% url 'Invoicee:modify-invoicee' invoicee.id %}" 
            hx-target="#invoicee-form-dialog"
            hx-swap="innerHTML"
            hx-push-url="false"
            hx-on:click="document.getElementById('invoicee-form-dialog').showModal()"
            type="button"
            helptext="{% translate 'InvoiceeModifyExplanation' %}">
            {% include './symbols/edit.svg' %}
        </button>
    </td>
    <td class="borderless">
        <button 
            type="button"
            helptext="{% translate 'AddInvoiceForInvoicee' %}"
            hx-get="{% url 'Invoice:add-invoice-for' invoicee.id %}"
            hx-target="#invoice-form-dialog"
            hx-on:Click="document.getElementById('invoice-form-dialog').showModal()"
            hx-swap="innerHTML">
            {% include './symbols/file-plus.svg' %}
        </button>
    </td>
    <td class="borderless">
        <button 
            type="button"
            helptext="{% translate 'AddEstimateForInvoicee' %}"
            hx-get="{% url 'Invoice:add-estimate-for' invoicee.id %}"
            hx-target="#invoice-form-dialog"
            hx-on:Click="document.getElementById('invoice-form-dialog').showModal()"
            hx-swap="innerHTML">
            {% include './symbols/shopping-bag.svg' %}
        </button>
    </td>
</tr>