Invoice/urls.py
from django.urls import path, register_converter
from .views import (
    download_invoice,
    delete_project,
    delete_fee,
    modify_invoice,
    modify_project,
    modify_fee,
    add_projectAndFeesToInvoice,
    add_feesToProject,
    create_creditNoteOfInvoice,
    add_invoice,
    add_invoice_for,
    validate_invoice,
    delete_invoice,
    add_estimate,
    add_estimate_for,
    invoice_estimate,
    delete_payment,
    download_receipt,
    InvoiceDetailView,
    InvoiceListView,
    EstimateListView,
    CreditNoteListView,
    PaymentCreateView,
    PaymentUpdateView,
    PaymentDetailView,
    PaymentListView,
)

from Core.views import DateConverter


register_converter(DateConverter, 'date')
app_name = 'Invoice'
urlpatterns = [
    path('', InvoiceListView.as_view(), name='index'),
    path('estimates', EstimateListView.as_view(), name='estimates'),
    path('creditNotes', CreditNoteListView.as_view(), name='creditNotes'),
    path(
        '<int:invoicer>/<int:invoicee>/<date:beginDate>/<date:endDate>',
        InvoiceListView.as_view(),
        name='index',
    ),
    path('addInvoice/', add_invoice, name='add-invoice'),
    path('addEstimate/', add_estimate, name='add-estimate'),
    path(
        'addInvoiceFor/<int:invoicee>',
        add_invoice_for,
        name='add-invoice-for',
    ),
    path(
        'addEstimateFor/<int:invoicee>',
        add_estimate_for,
        name='add-estimate-for',
    ),
    path('deleteInvoice/<int:invoice>', delete_invoice, name='delete-invoice'),
    path(
        'invoiceEstimate/<int:invoice>',
        invoice_estimate,
        name='invoice-estimate',
    ),
    path(
        'invoiceValidate/<int:invoice>',
        validate_invoice,
        name='validate-invoice',
    ),
    path(
        'createCreditNote/<int:invoice>',
        create_creditNoteOfInvoice,
        name='create-creditNote',
    ),
    path('preview/<slug:pk>', InvoiceDetailView.as_view(), name='preview'),
    path('download/<int:invoice>', download_invoice, name='download'),
    path('modify/<int:invoice>', modify_invoice, name='modify'),
    path('modifyProject/<int:project>', modify_project, name='modifyProject'),
    path('modifyFee/<int:fee>', modify_fee, name='modifyFee'),
    path(
        'addFeesToProject/<int:project>',
        add_feesToProject,
        name='addFeesToProject',
    ),
    path(
        'addProjectAndFees/<int:invoice>',
        add_projectAndFeesToInvoice,
        name="addProjectAndFeesToInvoice",
    ),
    path('deleteProject/<int:project>', delete_project, name='deleteProject'),
    path('deleteFee/<int:fee>', delete_fee, name='deleteFee'),
    path('updateFee/<int:fee>', modify_fee, name='updateFee'),
    path('payments', PaymentListView.as_view(), name='payments'),
    path('payment/<slug:pk>', PaymentDetailView.as_view(), name='payment'),
    path('addPayment', PaymentCreateView.as_view(), name='add-payment'),
    path(
        'updatePayment/<slug:pk>',
        PaymentUpdateView.as_view(),
        name='update-payment',
    ),
    path(
        'deletePayment/<int:payment>',
        delete_payment,
        name='delete-payment',
    ),
    path(
        'downloadReceipt/<int:payment>',
        download_receipt,
        name='download-receipt',
    ),
]

Invoicee/urls.py
from django.urls import path, register_converter
from .views import (
    InvoiceeListView,
    PrivateInvoiceeListView,
    InvoiceeDetailView,
    InvoiceeCreateView,
    InvoiceeUpdateView,
    PrivateInvoiceeCreateView,
)

from Core.views import DateConverter


register_converter(DateConverter, 'date')
app_name = 'Invoicee'
urlpatterns = [
    path('', InvoiceeListView.as_view(), name='invoicees'),
    path('private', PrivateInvoiceeListView.as_view(), name='pinvoicees'),
    path('detail/<slug:pk>', InvoiceeDetailView.as_view(), name='invoicee'),
    path('addInvoicee', InvoiceeCreateView.as_view(), name='add-invoicee'),
    path(
        'addPrivateInvoicee',
        PrivateInvoiceeCreateView.as_view(),
        name='add-private-invoicee',
    ),
    path(
        'modify/<slug:pk>',
        InvoiceeUpdateView.as_view(),
        name='modify-invoicee',
    ),
    path(
        'addInvoicee',
        InvoiceeCreateView.as_view(),
        name='add-invoicee',
    ),
]

home/urls.py
from django.urls import path, register_converter
from .views import (
    index,
    register_user,
    register_success,
)
from Core.views import DateConverter

register_converter(DateConverter, 'date')
app_name = 'home'
urlpatterns = [
    path('', index, name='index'),
    path(
        '<int:invoicer>/<date:beginDate>/<date:endDate>',
        index,
        name='index',
    ),
    path('register/', register_user, name='register'),
    path('registerSuccess/', register_success, name='registerSuccess')
]

templates/aside.html
{% load i18n %}
{% if user.is_authenticated %}
<aside>
    <div class="nav-box column">
        <ul>
            {% if user.is_staff %}
            <li><a href="{% url 'admin:index' %}" class="MainItem">{% translate 'ADMINSHORTCUTS' %}</a></li>
            {% if user.is_superuser %}
            <li><a href="{% url 'admin:Invoicer_invoicer_changelist' %}" class="SubItem">- {% translate 'INVOICERS' %}</a></li>
            {% endif %}
            <li><a href="{% url 'admin:Invoicee_invoicee_changelist' %}" class="SubItem">- {% translate 'INVOICEES' %}</a></li>
            <li><a href="{% url 'admin:Invoice_invoice_changelist' %}" class="SubItem">- {% translate 'INVOICES' %}</a></li>
            <li><a href="{% url 'admin:Invoice_project_changelist' %}" class="SubItem">- {% translate 'PROJECTS' %}</a></li>
            <li><a href="{% url 'admin:Invoice_fee_changelist' %}" class="SubItem">- {% translate 'Fees' %}</a></li>
            {% endif %}
            {% if not user.is_superuser %}
            <li><button 
                hx-indicator="#indicator"
                hx-get="{% url 'Invoice:add-estimate' %}" class="MainItem"
                hx-target="#invoice-form-dialog"
                hx-on:click="document.getElementById('invoice-form-dialog').showModal();"
                hx-swap="innerHTML"
                nonce={{request.csp_nonce}}
            >{% translate 'AddEstimate' %}</button></li>
            <li><button 
                hx-indicator="#indicator"
                hx-get="{% url 'Invoice:add-invoice' %}" class="MainItem"
                hx-target="#invoice-form-dialog"
                hx-on:click="document.getElementById('invoice-form-dialog').showModal();"
                hx-swap="innerHTML"
                nonce={{request.csp_nonce}}
            >{% translate 'AddInvoice' %}</button></li>
            <li><button 
                hx-indicator="#indicator"
                hx-get="{% url 'Invoice:add-payment' %}" class="MainItem"
                hx-target="#payment-form-dialog"
                hx-on:click="document.getElementById('payment-form-dialog').showModal();"
                hx-swap="innerHTML"
                nonce={{request.csp_nonce}}
            >{% translate 'AddPayment' %}</button></li>
            <li><button 
                hx-indicator="#indicator"
                hx-get="{% url 'Invoicee:add-invoicee' %}" class="MainItem"
                hx-target="#invoicee-form-dialog"
                hx-on:click="document.getElementById('invoicee-form-dialog').showModal();"
                hx-swap="innerHTML"
                nonce={{request.csp_nonce}}
            >{% translate 'AddInvoicee' %}</button></li>
            <li><button 
                hx-indicator="#indicator"
                hx-get="{% url 'Invoicee:add-private-invoicee' %}" class="MainItem"
                hx-target="#invoicee-form-dialog"
                hx-on:click="document.getElementById('invoicee-form-dialog').showModal();"
                hx-swap="innerHTML"
                nonce={{request.csp_nonce}}
            >{% translate 'AddPrivateInvoicee' %}</button></li>
            {% endif %}
            <li><a href="{% url 'kagi:two-factor-settings' %}" class="MainItem">{% translate 'AccountMFASetting' %}</a></li>
            {% block extraAsideItems %} {% endblock %}
        </ul>
    </div>
	<div class="form-aside-wrapper">
		<div class="helptext">{% translate 'ChooseTheLanguage' %}</div>
		<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
			<input name="next" type="hidden" value="{{ redirect_to }}">
			<select name="language">
				{% get_current_language as LANGUAGE_CODE %}
				{% get_available_languages as LANGUAGES %}
				{% get_language_info_list for LANGUAGES as languages %}
				{% for language in languages %}
				<option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
					{{ language.name_local }} ({{ language.code }})
				</option>
				{% endfor %}
			</select>
			<button type="submit">{% translate 'GO' %}</button>
		</form>
	</div>
	<div class="form-aside-wrapper">
		<form action="{% url 'logout' %}" method="post">
			{% csrf_token %}
			<button type="submit">{% translate 'Log Out' %}</button>
		</form>
	</div>
</aside>
{% endif %}

templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html 
  {% get_current_language as LANGUAGE_CODE %}
  {% if LANGUAGE_CODE == 'ar' %}
  dir="rtl"
  {% endif %}
  lang="fr" data-lt-installed="true"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="WebApplication for LAMOME Business">
    <meta name="keywords" content="">
    <meta name="author" content="Mohamed Ghazal">
    <meta name="referrer" content="origin">
    <meta name="robots" content="index, follow">
    <meta
      name="htmx-config"
      content='{
      "inlineScriptNonce": "{{ request.csp_nonce }}",
      "responseHandling":[
      {"code":"[23]..", "swap": true},
      {"code":"405", "swap": true, "error": false, "swapOverride": "location.reload()"},
      {"code":"4[1-9][1-4|6-7]", "swap": false, "error": true},
      {"code":"400", "swap": true, "target": "#invoicee-dialog-form", "error": true},
      {"code":"5..", "swap": false, "error": true},
      {"code":"...", "swap": true}
      ]
      }'
    />
    <link rel="stylesheet" href="{% static './css/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static './admin/css/vendor/select2/select2.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static './django_select2/django_select2.css' %}" media="screen">
    {% get_current_language as LANGUAGE_CODE %}
    {% if LANGUAGE_CODE == 'ar' %}
    <link rel="stylesheet" href="{% static './css/utils/arabic_extra.css' %}" media="screen">
    {% endif %}
    <link rel="icon" type="image/x-icon" href="{% static './img/favicon.ico' %}">
    <script src="{% url 'javascript-catalog' %}"></script>
    <script src="{% static './js/htmx.min.js' %}"></script>
    <script src="{% static './js/jquery.min.js' %}"></script>
    <script src="{% static './admin/js/vendor/select2/select2.full.min.js' %}"></script>
    {% if LANGUAGE_CODE == 'fr' %}
    <script src="{% static './admin/js/vendor/select2/i18n/fr.js' %}"></script>
    {% elif LANGUAGE_CODE == 'ar' %}
    <script src="{% static './admin/js/vendor/select2/i18n/ar.js' %}"></script>
    {% elif LANGUAGE_CODE == 'en-US' %}
    <script src="{% static './admin/js/vendor/select2/i18n/en.js' %}"></script>
    {% endif %}
    <script src="{% static './django_select2/django_select2.js' %}"></script>
    {% block title %} {% endblock %}
<link 
  rel="stylesheet" 
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" 
  integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" 
  crossorigin="anonymous" 
  referrerpolicy="no-referrer"/>
</head>
<body>
  {% include 'header.html' %}
  {% include 'aside.html' %}
  {% include './symbols/loader.svg' %}
  <main {% if not user.is_authenticated %} class="expanded" {% endif %} 
    hx-swap="innerHTML"
    hx-on:htmx:after-settle=" const arr = Array.from(document.getElementsByClassName('form-dialog')); arr.forEach(item => { item.close() }); "
  >
    {% block content %} {% endblock %}
  </main>
  {% include 'footer.html' %}
  <script defer nonce="{{ request.csp_nonce }}">
  $(document).keyup(function(e) {if (e.keyCode == 27) {window.location.reload();}})
  </script>
  <dialog id="invoicee-form-dialog" class="form-dialog"></dialog>
  <dialog id="invoice-form-dialog" class="form-dialog"></dialog>
  <dialog id="payment-form-dialog" class="form-dialog"></dialog>
</body>
</html>

templates/footer.html
{% load i18n %}
<footer>
	<div class="copyright">
		<div class="f-social">
			<a href="mailto:infos@lamome.business" class="footer-social"><i class="far fa-envelope"></i></a>
			<a href="https://www.linkedin.com/company/la-mome-business/" class="footer-social"><i class="fab fa-linkedin"></i></a>
			<a href="#" class="footer-social"><i class="fab fa-facebook"></i></a>
			LA MOME Business&copy; 2024
		</div>
	</div>
</footer>

templates/header.html
{% load i18n %}
{% load static %}
<header>
  <div class="brand-box">
    <img src="{% static 'img/lmmb-compact.svg' %}" alt="complete-logo" class="complete-logo">
  </div>
  <div class="nav-box">
    <ul>
      {% if user.is_authenticated %}
      <li><button 
        type="button" 
        hx-get="{% url 'home:index' %}" 
        hx-push-url="true" 
        hx-target="main" 
        hx-indicator="#indicator"
        hx-swap="innerHTML">
        {% translate 'Home' %}
      </button></li>
      {% if not user.is_superuser %}
      <li>
        <button 
          type="button" 
          hx-get="{% url 'Invoicee:invoicees' %}" 
          hx-push-url="true" 
          hx-target="main" 
          hx-indicator="#indicator"
          hx-swap="innerHTML">
          {% translate 'INVOICEES' %}
        </button>
      </li>
      <li>
        <button type="button" hx-get="{% url 'Invoicee:pinvoicees' %}" hx-push-url="true" hx-target="main" hx-swap="innerHTML" hx-indicator="#indicator">
          {% translate 'PrivateINVOICEES' %}
        </button>
      </li>
      <li>
        <button type="button" hx-get="{% url 'Invoice:index' %}" hx-push-url="true" hx-target="main" hx-swap="innerHTML" hx-indicator="#indicator">
          {% translate 'INVOICES' %}
        </button>
      </li>
      <li>
        <button type="button" hx-get="{% url 'Invoice:estimates' %}" hx-push-url="true" hx-target="main" hx-swap="innerHTML" hx-indicator="#indicator">
          {% translate 'Estimates' %}
        </button>
      </li>
      <li>
        <button type="button" hx-get="{% url 'Invoice:creditNotes' %}" hx-push-url="true" hx-target="main" hx-swap="innerHTML" hx-indicator="#indicator">
          {% translate 'CreditNotes' %}
        </button>
      </li>
      <li>
        <button type="button" hx-get="{% url 'Invoice:payments' %}" hx-push-url="true" hx-target="main" hx-swap="innerHTML" hx-indicator="#indicator">
          {% translate 'Payments' %}
        </button>
      </li>
      {% endif %}
      {% if user.is_superuser or user.is_staff %}
      <li><a href={% url 'admin:index' %}>{% translate 'ADMIN' %}</a></li>
      {% endif %}
      {% if user.is_superuser %}
      <li><a href={% url 'rosetta-old-home-redirect' %}>{% translate 'ROSETTA' %}</a></li>
      {% endif %}
      {% else %}
      <li><a href={% url 'login' %}>{% translate 'LOGIN' %}</a></li>
      <li><a href={% url 'home:register' %}>{% translate 'REGISTER' %}</a></li>
      {% endif %}
    </ul>
  </div>
</header>